# Generated by Django 5.1.2 on 2024-11-22 00:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sale_qr_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sale',
            name='qr_code',
        ),
    ]
