# Generated by Django 5.1.2 on 2024-11-22 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sale_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='qr_code',
            field=models.ImageField(blank=True, null=True, upload_to='qrcodes/'),
        ),
    ]
