# Generated by Django 5.1.2 on 2024-11-22 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sale_qr_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order_id',
            field=models.CharField(blank=True, max_length=15, null=True, unique=True),
        ),
    ]
