# Generated by Django 5.1.2 on 2024-11-26 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_sale_order_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sale',
            options={'ordering': ['-date_added']},
        ),
    ]
