# Generated by Django 5.1.2 on 2024-11-26 23:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_barcode_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='barcode_image',
        ),
    ]
